sign up fuctions init
rammyblog/ecommerce-microservice pull request #14
Opened 2022-07-07 07:58 UTC by AyoFayomi

2022-07-07 18:08 UTC, rammyblog commented on frontend/components/Products/SingleProduct.jsx
> +    <Container>
We agreed you'd take this out right? Or it looks fine now?

2022-07-07 18:08 UTC, rammyblog commented on frontend/components/Products/SingleProduct.jsx
> +    <Container>
We agreed you'd take this out right? Or it look fine now?

2022-07-07 18:09 UTC, rammyblog commented on frontend/package.json
> +    "react-toastify": "^9.0.5",
Is this necessary? I thought Chakra came with a toast
 You can uninstall it using `npm uninstall package name`

2022-07-07 18:10 UTC, rammyblog commented on frontend/pages/_app.js
> +import "react-toastify/dist/ReactToastify.css";
Remove this

2022-07-07 18:15 UTC, rammyblog commented on frontend/pages/_app.js
> +import "react-toastify/dist/ReactToastify.css";
Remove this

2022-07-07 18:15 UTC, rammyblog commented on frontend/pages/_app.js
> +        <Container maxW="100vw" >
Restore the initial container

2022-07-07 18:16 UTC, rammyblog commented on frontend/pages/register.js
> +                      { pending ? "Loading..." :"REGISTER"}
You can just disable the button when pending

2022-07-07 18:17 UTC, rammyblog commented on frontend/store/products/actions.js
> +export const register = createAsyncThunk(
Move this function to it's own folder

2022-07-07 18:18 UTC, rammyblog requested changes
I have left some comments

2022-07-08 00:00 UTC, AyoFayomi commented on frontend/pages/register.js
> +                      { pending ? "Loading..." :"REGISTER"}
The button disables that way also

2022-07-10 12:42 UTC, rammyblog approved these changes

2022-07-10 12:42 UTC, merged